---
# See https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  tags: powershell

- name: Download MSProd source package
  ansible.builtin.get_url:
    url: "{{ msprod_source_package_url }}"
    dest: "{{ msprod_local_path }}"
    mode: '0644'
  when: "'packages-microsoft-prod' not in ansible_facts.packages"
  register: msprod_source_package_downloaded
  tags: powershell

- name: Install MSProd source package
  ansible.builtin.command: dpkg -i {{ msprod_local_path }}
  when: msprod_source_package_downloaded.changed
  tags: powershell

- name: Remove MSProd source package
  ansible.builtin.file:
    path: "{{ msprod_local_path }}"
    state: absent
  when: msprod_source_package_downloaded.changed
  register: msprod_source
  tags: powershell

- name: Update apt sources
  ansible.builtin.command: apt-get update
  when: msprod_source.changed
  tags: powershell

- name: Install Powershell packages
  ansible.builtin.apt:
    name: '{{ powershell_apt_packages }}'
    state: present
  tags: powershell
