---
- name: Determine if MSProd gpg keyring already exists
  stat:
    path: "{{ msprod_gpg_keyring }}"
  register: msprod_gpg_keyring_file
  tags: powershell

- name: Download MSProd source package
  ansible.builtin.get_url:
    url: "{{ https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb  }}"
    dest: /tmp/packages-microsoft-prod.deb
    mode: '0644'
  when: not msprod_gpg_keyring_file.stat.exists
  register: msprod_source_package_downloaded
  tags: powershell

- name: Install MSProd source package
  ansible.builtin.command: dpkg -i /tmp/packages-microsoft-prod.deb
  when: msprod_source_package_downloaded.changed
  tags: powershell

- name: Remove MSProd source package
  ansible.builtin.file:
    path: /tmp/packages-microsoft-prod.deb
    state: absent
  when: msprod_source_package_downloaded.changed
  tags: powershell

- name: Install Powershell packages
  ansible.builtin.apt:
    name: '{{ powershell_apt_packages }}'
    state: present
  tags: powershell
