---
- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat={{ elastic_stack_version }}
    state: present
  tags: sof-elk_filebeat

- name: Configure filebeat
  ansible.builtin.file:
    src: '/usr/local/sof-elk/lib/configfiles/filebeat.yml'
    dest: '/etc/filebeat/filebeat.yml'
    state: link
    force: yes
  notify: restart filebeat
  tags: sof-elk_filebeat

- name: Create filebeat input base directory
  ansible.builtin.file:
    dest: '/logstash'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create filebeat input directories
  ansible.builtin.file:
    dest: '/logstash/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 01777
  with_items:
    - syslog
    - nfarch
    - httpd
    - passivedns
    - zeek
    - kape
    - plaso
    - microsoft365
    - azure
    - aws
    - gcp
    - gws
    - kubernetes
  notify: restart filebeat
  tags: sof-elk_filebeat

- name: Start and enable Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    enabled: yes
    state: started
  tags: sof-elk_filebeat
