---
- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present
  tags: sof-elk_elasticsearch

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
  tags: sof-elk_elasticsearch

- name: Create Elasticsearch systemd override directory
  file:
    dest: '/etc/systemd/system/elasticsearch.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart elasticsearch
  tags: sof-elk_elasticsearch

- name: Override Elasticsearch systemd limits
  copy:
    src: 'systemd_override.conf'
    dest: '/etc/systemd/system/elasticsearch.service.d/override.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch
  tags: sof-elk_elasticsearch

- name: Configure Elasticsearch
  copy:
    src: 'elasticsearch.yml'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  tags: sof-elk_elasticsearch

- name: Run daemon-reload so service can start
  command: 'systemctl daemon-reload'
  tags: sof-elk_elasticsearch

- name: Start and Enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  tags: sof-elk_elasticsearch
