---
- name: Install Elasticsearch
  ansible.builtin.apt:
    name: elasticsearch={{ elastic_stack_version }}
    state: present
  tags: elasticsearch

- name: Set permissions on Elasticsearch data directory
  ansible.builtin.file:
    path: /var/lib/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
  tags: elasticsearch

- name: Create Elasticsearch systemd override directory
  ansible.builtin.file:
    dest: '/etc/systemd/system/elasticsearch.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart elasticsearch
  tags: elasticsearch

- name: Override Elasticsearch systemd limits
  ansible.builtin.copy:
    src: 'systemd_override.conf'
    dest: '/etc/systemd/system/elasticsearch.service.d/override.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch
  tags: elasticsearch

- name: Configure Elasticsearch
  ansible.builtin.copy:
    src: 'elasticsearch.yml'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  tags: elasticsearch

- name: Run daemon-reload so service can start
  ansible.builtin.command: 'systemctl daemon-reload'
  tags: elasticsearch

- name: Start and Enable Elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: yes
    state: started
  tags: elasticsearch
