---
msprod_gpg_keyring: /usr/share/keyrings/microsoft-prod.gpg
#TODO: Move the key to a separate role (same key for azure-cli and powershell)

msprod_source_package_url: https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
msprod_local_path: /tmp/packages-microsoft-prod.deb
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2024 Lewes Technology Consulting, LLC

# x86 uses apt install
powershell_apt_packages:
  - powershell

# arm uses .tar.gz install.  (related; WHY, MICROSOFT, WHY?!??!?!?)
powershell_version: 7.4.6
powershell_archive: powershell-{{ powershell_version }}-linux-arm64.tar.gz
powershell_installation_directory: /opt/microsoft/powershell/7
powershell_archive_url: https://github.com/PowerShell/PowerShell/releases/download/v{{ powershell_version }}/{{ powershell_archive }}
