---
- name: Install Azure CLI dependencies
  ansible.builtin.apt:
    name: '{{ azure_cli_dependencies }}'
    state: present
  tags: azure-cli

- name: Determine if gpg keyring already exists
  stat:
    path: "{{ azure_cli_gpg_keyring }}"
  register: azure_gpg_keyring_file
  tags: azure-cli

- name: Download armored Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ azure_cli_armored_keyring }}"
    mode: '0644'
  when: not azure_gpg_keyring_file.stat.exists
  register: azure_armored_gpg_key_downloaded
  tags: azure-cli

- name: Convert GPG key to binary form
  ansible.builtin.command: gpg --dearmor -o {{ azure_cli_gpg_keyring }} {{ azure_cli_armored_keyring }}
  when: azure_armored_gpg_key_downloaded.changed
  tags: azure-cli

- name: Remove armored Microsoft GPG key
  ansible.builtin.file:
    path: "{{ azure_cli_armored_keyring }}"
    state: absent
  when: azure_armored_gpg_key_downloaded.changed
  tags: azure-cli

- name: Install Microsoft Azure source definition file
  ansible.builtin.template:
    src: azure-cli.sources.j2
    dest: /etc/apt/sources.list.d/azure-cli.sources
    mode: '0644'
  register: azure_source
  tags: azure-cli

- name: Update apt sources
  ansible.builtin.command: apt-get update
  when: azure_source.changed
  tags: azure-cli

- name: Install Azure packages
  ansible.builtin.apt:
    name: '{{ azure_apt_packages }}'
    state: present
  tags: azure-cli
