---
- name: Wait for Elasticsearch to be ready
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/wait_for_es.sh'
  tags: sof-elk_finalize

- name: Run the post-merge script, which also loads all dashboards
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/post_merge.sh'
  tags: sof-elk_finalize

- name: Restart Kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  tags: sof-elk_finalize

# first change the current ssh user to the new user
- name: Switch current user to elk_user
  ansible.builtin.set_fact:
     original_user: "{{ ansible_user }}"
     ansible_user: "elk_user"
  tags: sof-elk_finalize

# force remove original_user
- name: Remove current user ({{ original_user }}) if it's not "elk_user"
  become: yes
  ansible.builtin.user:
    name: "{{ original_user }}"
    state: absent
    remove: yes
    force: yes
  when: "original_user != new_user"
  tags: sof-elk_finalize

- name: Reboot system
  ansible.builtin.reboot:
    msg: "Rebooting in 60 seconds. Press Ctrl-C to cancel."
    pre_reboot_delay: 60