---
- name: Install Kibana
  apt:
    name: kibana={{ elastic_stack_version }}
    state: present
  tags: sof-elk_kibana

- name: Configure Kibana
  ansible.builtin.copy:
    src: 'kibana.yml'
    dest: '/etc/kibana/kibana.yml'
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
  tags: sof-elk_kibana

- name: Open firewall ports
  ansible.posix.firewalld:
    port: 5601/tcp
    permanent: yes
    state: enabled
  notify: restart firewalld
  tags: sof-elk_kibana
  #when: not (ansible_system_vendor == 'Microsoft Corporation' and ansible_virtualization_type == 'VirtualPC')

- name: Enable and start Kibana service
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    state: started
  tags: sof-elk_kibana
