---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2024 Lewes Technology Consulting, LLC

- name: Install Kibana
  apt:
    name: kibana={{ elastic_stack_version }}
    state: present
  tags: kibana

- name: Configure Kibana
  ansible.builtin.copy:
    src: 'kibana.yml'
    dest: '/etc/kibana/kibana.yml'
    owner: root
    group: root
    mode: 0644
  register: kibana_config
  tags: kibana

- name: Restart Kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  when: kibana_config.changed
  tags: kibana

- name: Open firewall ports
  ansible.posix.firewalld:
    port: 5601/tcp
    permanent: yes
    state: enabled
  register: firewall_port
  #when: not (ansible_system_vendor == 'Microsoft Corporation' and ansible_virtualization_type == 'VirtualPC')
  tags: kibana

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  when: firewall_port.changed
  tags: kibana

- name: Enable and start Kibana service
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    state: started
  tags: kibana
