---
# TODO: for some reason this is not working right now
- name: Install Logstash
  ansible.builtin.apt:
#    name: logstash={{ elastic_stack_version }}
    name: logstash
    state: present
  tags: sof-elk_logstash

# TODO: this may not be needed since we previously installed the dpkg trigger
- name: Install Logstash Plugins
  community.general.logstash_plugin:
    name: '{{ item }}'
    state: present
  with_items:
    - logstash-input-relp
    - logstash-input-google_pubsub
    - logstash-filter-tld
    - logstash-filter-rest
    - logstash-filter-json_encode
  notify: restart logstash
  tags: sof-elk_logstash

- name: Set Logstash JVM options
  ansible.builtin.lineinfile:
    dest: '/etc/logstash/jvm.options'
    regexp: "^{{ item.parameter | regex_escape() }}"
    line: "{{ item.parameter }}{{ item.value }}"
  with_items:
    - { parameter: '-Xms', value: '750m' }
    - { parameter: '-Xss', value: '4m' }
  notify: restart logstash
  tags: sof-elk_logstash

- name: Get list of all configfiles
  ansible.builtin.find:
    paths: '/usr/local/sof-elk/configfiles/'
    file_type: file
  register: configfile_results
  tags: sof-elk_logstash

- name: Set symlinks for pipeline configuration
  ansible.builtin.file:
    src: '/usr/local/sof-elk/configfiles/{{ item.path | basename }}'
    dest: '/etc/logstash/conf.d/{{ item.path | basename }}'
    state: link
  with_items:
    - '{{ configfile_results.files }}'
  notify: restart logstash
  tags: sof-elk_logstash

- name: Configure Logstash
  ansible.builtin.copy:
    src: 'logstash.yml'
    dest: '/etc/logstash/logstash.yml'
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  tags: sof-elk_logstash

- name: Start and Enable Logstash service
  ansible.builtin.systemd:
    name: logstash
    enabled: yes
    state: started
  tags: sof-elk_logstash
